f_name_23 = [
        'fHogaPerTrade',
        'fHogaSpeedCur',
        'fISlope',
        'fMinusCnt07',
        'fMinusCnt09',
        'fOnlyUpPowerJar',
        'fPlusCnt07',
        'fPlusCnt09',
        'fPower',
        'fPowerJar',
        'fPowerWithOutGap',
        'fPureBuyCur',
        'fRSlope',
        'fSharePerTrade',
        'fSpeedCur',
        'fStartGap',
        'fTradeCur',
        'nCandleTwoOverRealCnt',
        'nCandleTwoOverRealNoLeafCnt',
        'nFakeResistCnt',
        'nRqTime',
        'nShootingCnt',
        'nTotalTradeVolumeRanking'
]

f_name_102 = [   
        'nBuyStrategyIdx',
        'nRqTime' , 
        'fStartGap' ,
        'fPowerWithOutGap' , 
        'fPower' , 
        'fPlusCnt07' , 
        'fMinusCnt07' , 
        'fPlusCnt09' , 
        'fMinusCnt09' ,
        'fPowerJar' , 
        'fOnlyDownPowerJar' , 
        'fOnlyUpPowerJar' , 
        'nTradeCnt' , 
        'nChegyulCnt' , 
        'nHogaCnt' , 
        'nNoMoveCnt' , 
        'nFewSpeedCnt' ,
        'nMissCnt' , 
        'lTotalTradeVolume' , 
        'lTotalBuyVolume' , 
        'lTotalSellVolume' ,
        'nAccumUpDownCount' ,
        'fAccumUpPower' , 
        'fAccumDownPower' ,
        'lTotalTradePrice' , 
        'lTotalBuyPrice' , 
        'lTotalSellPrice' , 
        'lMarketCap' , 
        'nAccumCountRanking' , 
        'nMarketCapRanking' , 
        'nPowerRanking' , 
        'nTotalBuyPriceRanking' , 
        'nTotalBuyVolumeRanking' ,
        'nTotalTradePriceRanking' ,
        'nTotalTradeVolumeRanking' ,
        'nTotalRank' , 
        'nMinuteTotalRank' , 
        'nMinuteTradePriceRanking' ,
        'nMinuteTradeVolumeRanking' , 
        'nMinuteBuyPriceRanking' , 
        'nMinuteBuyVolumeRanking' ,
        'nMinutePowerRanking' , 
        'nMinuteCountRanking' ,
        'nMinuteUpDownRanking' ,
        'nFakeBuyCnt' , 
        'nFakeAssistantCnt' ,
        'nFakeResistCnt' , 
        'nPriceUpCnt' , 
        'nPriceDownCnt' ,
        'nTotalFakeCnt' ,
        'nTotalFakeMinuteCnt' ,
        'nUpCandleCnt' , 
        'nDownCandleCnt' ,
        'nUpTailCnt' , 
        'nDownTailCnt' ,
        'nShootingCnt' ,
        'nCandleTwoOverRealCnt' ,
        'nCandleTwoOverRealNoLeafCnt' , 
        'fSpeedCur' , 
        'fHogaSpeedCur' ,
        'fTradeCur' , 
        'fPureTradeCur' , 
        'fPureBuyCur' , 
        'fHogaRatioCur' ,  
        'fSharePerHoga' , 
        'fSharePerTrade' ,
        'fHogaPerTrade' , 
        'fTradePerPure' , 
        'fMaDownFsVal' , 
        'fMa20mVal' , 
        'fMa1hVal' ,
        'fMa2hVal' ,
        'fMaxMaDownFsVal' ,
        'fMaxMa20mVal' ,
        'fMaxMa1hVal' ,
        'fMaxMa2hVal' ,
        'nMaxMaDownFsTime' ,
        'nMaxMa20mTime' ,
        'nMaxMa1hTime' ,
        'nMaxMa2hTime' ,
        'nDownCntMa20m' ,
        'nDownCntMa1h' ,
        'nDownCntMa2h' ,
        'nUpCntMa20m' ,
        'nUpCntMa1h' ,
        'nUpCntMa2h' ,
        'fMSlope' ,
        'fISlope' ,
        'fTSlope' ,
        'fHSlope' ,
        'fRSlope' ,
        'fDSlope' ,
        'fMAngle' ,
        'fIAngle' ,
        'fTAngle' ,
        'fHAngle' ,
        'fRAngle' ,
        'fDAngle' ,
        'nCrushCnt' ,
        'nCrushUpCnt' ,
        'nCrushDownCnt' ,
        'nCrushSpecialDownCnt' 
]

f_name_102_renew_fake = [   
        'nAccessFakeStrategyIdx',
        'nRqTime' , 
        'fStartGap' ,
        'fPowerWithOutGap' , 
        'fPower' , 
        'fPlusCnt07' , 
        'fMinusCnt07' , 
        'fPlusCnt09' , 
        'fMinusCnt09' ,
        'fPowerJar' , 
        'fOnlyDownPowerJar' , 
        'fOnlyUpPowerJar' , 
        'nRealBuyCnt' , 
        'nChegyulCnt' , 
        'nHogaCnt' , 
        'nNoMoveCnt' , 
        'nFewSpeedCnt' ,
        'nMissCnt' , 
        'lTotalTradeVolume' , 
        'lTotalBuyVolume' , 
        'lTotalSellVolume' ,
        'nAccumUpDownCount' ,
        'fAccumUpPower' , 
        'fAccumDownPower' ,
        'lTotalTradePrice' , 
        'lTotalBuyPrice' , 
        'lTotalSellPrice' , 
        'lMarketCap' , 
        'nAccumCountRanking' , 
        'nMarketCapRanking' , 
        'nPowerRanking' , 
        'nTotalBuyPriceRanking' , 
        'nTotalBuyVolumeRanking' ,
        'nTotalTradePriceRanking' ,
        'nTotalTradeVolumeRanking' ,
        'nTotalRank' , 
        'nMinuteTotalRank' , 
        'nMinuteTradePriceRanking' ,
        'nMinuteTradeVolumeRanking' , 
        'nMinuteBuyPriceRanking' , 
        'nMinuteBuyVolumeRanking' ,
        'nMinutePowerRanking' , 
        'nMinuteCountRanking' ,
        'nMinuteUpDownRanking' ,
        'nFakeBuyCnt' , 
        'nFakeAssistantCnt' ,
        'nFakeResistCnt' , 
        'nFakeVolatilityCnt' , 
        'nFakeDownCnt' ,
        'nTotalFakeCnt' ,
        'nTotalFakeMinuteCnt' ,
        'nOnePerCandleCnt' , 
        'nDownCandleCnt' ,
        'nUpTailCnt' , 
        'nDownTailCnt' ,
        'nThreePerCandleCnt' ,
        'nTwoPerCandleCnt' ,
        'nTwoPerCandleCnt' , 
        'fSpeedCur' , 
        'fHogaSpeedCur' ,
        'fTradeCur' , 
        'fPureTradeCur' , 
        'fPureBuyCur' , 
        'fHogaRatioCur' ,  
        'fSharePerHoga' , 
        'fSharePerTrade' ,
        'fHogaPerTrade' , 
        'fTradePerPure' , 
        'nFb' , 
        'nFb' , 
        'nFb' ,
        'nFb' ,
        'nTodayMaxPrice' ,
        'nTodayMaxPrice' ,
        'nTodayMaxPrice' ,
        'nTodayMaxPrice' ,
        'nTodayMaxTime' ,
        'nTodayMaxTime' ,
        'nTodayMaxTime' ,
        'nTodayMaxTime' ,
        'nDownCntMa20m' ,
        'nDownCntMa1h' ,
        'nDownCntMa2h' ,
        'nUpCntMa20m' ,
        'nUpCntMa1h' ,
        'nUpCntMa2h' ,
        'fMSlope' ,
        'fISlope' ,
        'fTSlope' ,
        'fHSlope' ,
        'fRSlope' ,
        'fDSlope' ,
        'fMAngle' ,
        'fIAngle' ,
        'fTAngle' ,
        'fHAngle' ,
        'fRAngle' ,
        'fDAngle' ,
        'nCrushCnt' ,
        'nCrushUpCnt' ,
        'nCrushDownCnt' ,
        'nCrushSpecialDownCnt' 
]


f_name_102_renew_buy = [   
        'nBuyStrategyIdx',
        'nRqTime' , 
        'fStartGap' ,
        'fPowerWithOutGap' , 
        'fPower' , 
        'fPlusCnt07' , 
        'fMinusCnt07' , 
        'fPlusCnt09' , 
        'fMinusCnt09' ,
        'fPowerJar' , 
        'fOnlyDownPowerJar' , 
        'fOnlyUpPowerJar' , 
        'nRealBuyCnt' , 
        'nChegyulCnt' , 
        'nHogaCnt' , 
        'nNoMoveCnt' , 
        'nFewSpeedCnt' ,
        'nMissCnt' , 
        'lTotalTradeVolume' , 
        'lTotalBuyVolume' , 
        'lTotalSellVolume' ,
        'nAccumUpDownCount' ,
        'fAccumUpPower' , 
        'fAccumDownPower' ,
        'lTotalTradePrice' , 
        'lTotalBuyPrice' , 
        'lTotalSellPrice' , 
        'lMarketCap' , 
        'nAccumCountRanking' , 
        'nMarketCapRanking' , 
        'nPowerRanking' , 
        'nTotalBuyPriceRanking' , 
        'nTotalBuyVolumeRanking' ,
        'nTotalTradePriceRanking' ,
        'nTotalTradeVolumeRanking' ,
        'nTotalRank' , 
        'nMinuteTotalRank' , 
        'nMinuteTradePriceRanking' ,
        'nMinuteTradeVolumeRanking' , 
        'nMinuteBuyPriceRanking' , 
        'nMinuteBuyVolumeRanking' ,
        'nMinutePowerRanking' , 
        'nMinuteCountRanking' ,
        'nMinuteUpDownRanking' ,
        'nFakeBuyCnt' , 
        'nFakeAssistantCnt' ,
        'nFakeResistCnt' , 
        'nFakeVolatilityCnt' , 
        'nFakeDownCnt' ,
        'nTotalFakeCnt' ,
        'nTotalFakeMinuteCnt' ,
        'nOnePerCandleCnt' , 
        'nDownCandleCnt' ,
        'nUpTailCnt' , 
        'nDownTailCnt' ,
        'nThreePerCandleCnt' ,
        'nTwoPerCandleCnt' ,
        'nTwoPerCandleCnt' , 
        'fSpeedCur' , 
        'fHogaSpeedCur' ,
        'fTradeCur' , 
        'fPureTradeCur' , 
        'fPureBuyCur' , 
        'fHogaRatioCur' ,  
        'fSharePerHoga' , 
        'fSharePerTrade' ,
        'fHogaPerTrade' , 
        'fTradePerPure' , 
        'nFb' , 
        'nFb' , 
        'nFb' ,
        'nFb' ,
        'nTodayMaxPrice' ,
        'nTodayMaxPrice' ,
        'nTodayMaxPrice' ,
        'nTodayMaxPrice' ,
        'nTodayMaxTime' ,
        'nTodayMaxTime' ,
        'nTodayMaxTime' ,
        'nTodayMaxTime' ,
        'nDownCntMa20m' ,
        'nDownCntMa1h' ,
        'nDownCntMa2h' ,
        'nUpCntMa20m' ,
        'nUpCntMa1h' ,
        'nUpCntMa2h' ,
        'fMSlope' ,
        'fISlope' ,
        'fTSlope' ,
        'fHSlope' ,
        'fRSlope' ,
        'fDSlope' ,
        'fMAngle' ,
        'fIAngle' ,
        'fTAngle' ,
        'fHAngle' ,
        'fRAngle' ,
        'fDAngle' ,
        'nCrushCnt' ,
        'nCrushUpCnt' ,
        'nCrushDownCnt' ,
        'nCrushSpecialDownCnt' 
]